/// Flutter icons SendLoveIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SendLoveIcons
///      fonts:
///       - asset: fonts/SendLoveIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SendLoveIcons {
  SendLoveIcons._();

  static const _kFontFam = 'SendLoveIcons';
  static const String? _kFontPkg = null;

  static const IconData heart = IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartbeat = IconData(0xf21e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_holding_heart = IconData(0xf4be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grin_hearts = IconData(0xf584, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kiss_wink_heart = IconData(0xf598, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
